- package-lock.json
- package.json
- src/App.tsx
- src/pages/Home.tsx
> chore: react-router 설정

- .github/workflows/deploy.yml
>  [Feature] 웹페이지 배포 CICD를 구축하라 #3 

- src/pages/Home.tsx
> [feature] 배포를 테스트하기 위해 에러를 고쳐라 #3

- .github/workflows/deploy.yml
> [feature] CICD 배포 이슈를 고쳐라 #3

- package-lock.json
- package.json
- src/App.tsx
- src/pages/SurveySpareTime/index.tsx
- src/pages/stores/spareTimeStore.ts
틈새 시간 묻기  페이지 구현 
- RangeBar 컴포넌트는 상태 업데이트 체크를 위해 임시로 만들었어요. 추후 UI 사용시 업데이트 가능합니다.
- zustand 전역상태 라이브러리 추가 및 spareTimeStore생성( 선택한 spareTime은 할일찾기에서도 공유)
> [Feature/asking-spare-time]  틈새 시간 묻기 페이지 구현

- src/data/todoRecommendData.json
> chore: mockData 추가

- src/pages/Home.tsx
- src/pages/OnBoarding.tsx
- vite.config.ts
> [Feature] 배포가 올바르게 되도록 환경설정을 고쳐라

- package-lock.json
- package.json
> [feature] 빌드 이슈를 고치기 위해 새로운 패키지를 추가하라

- README.md
> [Feature] 티클리 웹페이지를 구축하라 #3

- src/hooks/useOnboarding.ts
- src/pages/Home.tsx
> [Feature] 라우팅 구조를 개선하라

- src/pages/SurveySpareTime/index.tsx
- src/pages/Todos.tsx
- src/pages/TodosFind.tsx
> [Feature] 라우팅 경로를 업데이트 하라 #18

- index.html
- src/App.tsx
- src/components/TodoMemoryColorStandardPopup.tsx
- src/components/TodoMemoryDatePopup.tsx
- src/main.tsx
- src/pages/TodosMemory.tsx
> [Feature] 기록 페이지를 구축하라 #21

- src/App.tsx
- src/components/ProgressTimerQuitPopup.tsx
- src/pages/CompletedTimer.tsx
- src/pages/ProgressTimer.tsx
>  [Feature] 타이머 페이지를 구축하라 #23

- src/pages/Todos.tsx
> fix: RangeSlider 오류로 주석처리

- src/pages/Todos.tsx
> #27 fix: RangeSlider 부분 수정

- src/App.css
- src/index.css
- src/layout/MobileLayout.tsx
- src/pages/CompletedTimer.tsx
- src/pages/Home.tsx
- src/pages/OnboardingPage.tsx
- src/pages/ProgressTimer.tsx
- src/pages/SurveySpareTime/index.tsx
- src/pages/Todos.tsx
- src/pages/TodosFind.tsx
- src/pages/TodosMemory.tsx
> Feature/30 feature mobilelayout추가 #30

- src/App.css
- src/components/RangeSlider.tsx
- src/layout/MobileLayout.tsx
- src/pages/SurveySpareTime/index.tsx
- src/pages/TodosFind.tsx
- src/stores/recommendTodoFilterStore.ts
> Feature/33 feature materialui rangeslider 컴포넌트 생성

- src/App.css
- src/hooks/useProgressTimerPage.ts
- src/pages/ProgressTimer.tsx
> [Feature] 타이머 기능을 구현하라

- src/hooks/useProgressTimerPage.ts
- src/pages/ProgressTimer.tsx
> [Feature] 타이머 기능을 업데이트하라 #37

- src/pages/Todos.tsx
> fix: 충돌 리졸브

- src/pages/Todos.tsx
- src/pages/TodosFind.tsx
> fix: 빌드실패 개선

- package-lock.json
- src/App.tsx
- src/pages/Home.tsx
- src/pages/OnboardingPage.tsx
- src/pages/SurveySpareTime/index.tsx
- src/pages/TodosFind.tsx
- src/theme.ts
> [Feature]feature/55 feature 공통 cta 버튼 적용 #55 

- src/pages/TodosFind.tsx
> [FIX] fix: 사용하지 않은 컴포넌트 삭제 빌드실패원인픽스

- src/pages/Home.tsx
> #54 design: 티클리 글자 스타일 적용

- src/pages/Home.tsx
> fix: build 실패 고치기

- src/components/ProgressTimerQuitPopup.tsx
- src/pages/CompletedTimer.tsx
- src/pages/ProgressTimer.tsx
> [Feature] 타이머 UI를 업데이트 하라

- src/App.css
- src/App.tsx
- src/components/Button.tsx
- src/layout/MobileLayout.tsx
- src/pages/Home.tsx
- src/pages/SurveySpareTime/index.tsx
> feat: Mobilelayout vertical가운데 정렬 삭제, 엘리먼트가 상단에서 시작하도록

- src/components/RangeSlider.tsx
- src/pages/SurveySpareTime/index.tsx
> [Feature] feat: 시간 range slider 스타일링 추가 #68

- src/pages/Home.css
- src/pages/Home.tsx
> chore: 티클리 타이틀 위쪽 여백 추가가

- src/pages/Home.css
- src/pages/Home.tsx
> chore: 티클리 타이틀 위치 재배치

- src/pages/Todos.tsx
> #59 design 할일 추가 모달 css 작업 진행중

- src/pages/Todos.tsx
> #59 design: 할일 추가 모달 CSS 작업 완료

- package-lock.json
- package.json
- src/App.tsx
- src/components/TodoMemoryDatePopup.tsx
- src/pages/TodosMemory.tsx
> [Feature] 캘린더 기능을 업데이트 하라

- src/pages/Todos.tsx
> fix: 볼 것 추가 서비스준비중 모달창으로 변경

- src/components/BottomNavbar.tsx
> [FEATURE]feat: 하단 메뉴 아이콘 추가

- src/components/BottomNavbar.tsx
> feat: 배포 실패 픽스

- src/components/BottomNavbar.tsx
> feat: rollback

- src/components/BottomNavbar.css
- src/components/BottomNavbar.tsx
- src/pages/Todos.tsx
- src/pages/TodosFind.tsx
- src/pages/TodosMemory.tsx
> #98 design: UI 위치 수정
